// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homepage-variants/Concierge.tsx": () => import("../components/mockups/homepage-variants/Concierge.tsx"),
  "./components/mockups/homepage-variants/Immersion.tsx": () => import("../components/mockups/homepage-variants/Immersion.tsx"),
  "./components/mockups/homepage-variants/PlannerBoard.tsx": () => import("../components/mockups/homepage-variants/PlannerBoard.tsx")
};
